#!/bin/sh
##############################################################################
# Run Navier--Stokes solver regression checks.
# $Id: testregress,v 8.1 2015/04/20 11:14:18 hmb Exp $

case $# in
0) echo "usage: testregress new_code_version"; exit 0
esac

CODE=$1
MESHDIR=../mesh
PATH=.:$PATH

for i in taylor2 kovas1 taylor3 taylor4 taylor5 kovas2 kovas3 \
         kovas4 kovas5 tube1 tube2 tube3 sbr tc1 cylkov2
do
  if test ! -f $i
  then
    cp $MESHDIR/$i .
  fi
  compare $i > $i.rst
  enumerate -O3 $i > $i.num
  $CODE -chk $i >/dev/null 2>&1
  compare -n $i $i.fld > /dev/null 2> $i.new
  cmp -s $i.new ../regress/$i.ok
  case $? in
  0) echo passed: $i ;;
  1) echo failed: $i ;;
  esac
  rm $i*
done
